name: Deploy API project to Azure Functions

on:
  push:
    branches:
      - master

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   HARVESTER_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'krumelurdashboardapi'  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/API'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.300'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checking out code'
      uses: actions/checkout@master

    - name: Setting up dotnet ${{ env.DOTNET_VERSION }} environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Building project in folder {{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Publishing to Azure Functions ${{ env.AZURE_FUNCTIONAPP_NAME }}'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.HARVESTER_PUBLISH_PROFILE }}