name: Deploy Blazor Client to Azure

on:
  push:
    branches:
      - master

env:
  CLIENT_APP_PROJECT_PATH: 'src/Client/Client.csproj' 
  CLIENT_APP_CONFIGURATION: 'Release'
  CLIENT_APP_DIST_FOLDER: 'src/Client/bin/Release/netstandard2.1/publish/wwwroot'
  DOTNET_VERSION: '3.1.301'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checking out code'
      uses: actions/checkout@master
      
    - name: 'Setting up .NET ${{ env.DOTNET_VERSION }} environment'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Building client project from ${{ env.CLIENT_APP_PROJECT_PATH }}'
      shell: bash
      run: dotnet publish ${{ env.CLIENT_APP_PROJECT_PATH }} --configuration ${{ env.CLIENT_APP_CONFIGURATION }}

    - name: 'Deploying to blob storage'
      uses: krumelur/Azure-Storage-Action@master
      with:
        enabled-static-website: 'true'
        index-document: 'index.html'
        error-document: 'index.html'
        folder: '${{ env.CLIENT_APP_DIST_FOLDER }}'
        connection-string: ${{ secrets.DASHBOARD_BLOB_STORAGE_CONNECTION_STRING }}